### ISSUE TITLE
Unhandled Rejection (TypeError): (0 , _users.getUsersCount) is not a function

### ISSUE THREAD

**Issue by giantthinker** [jurkian/react-bank#4] opened 2019-11-07 14:26 UTC
×
Unhandled Rejection (TypeError): (0 , _users.getUsersCount) is not a function
Home._callee$
src/containers/Home/index.js:34
  31 | }
  32 | 
  33 | async componentDidMount() {
> 34 |    const usersCount = await getUsersCount();
  35 | 
  36 |    if (usersCount) {
  37 |       this.setState({
View compiled
▶ 28 stack frames were collapsed.

**Comment by jurkian** [comment] 2019-11-07 16:16
I can't reproduce it either, just like the previous error.
Make sure you have the latest version installed and if you can provide any other details - that would be really helpful to debug

**Comment by jurkian** [comment] 2019-11-08 09:38
This one should be fixed now. There was 1 file change (web) that I didn't see on the files list. Get the recent master and try it

**Closed** 2019-11-08 15:17 UTC
